name: tedx_sit
description: TEDxSiddagangaInstituteOfTechnology.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  firebase
  firebase_core: ^1.0.2
  cloud_firestore: ^1.0.3
  firebase_storage: ^8.0.1

#  cached network image
  cached_network_image: ^2.2.0+1

# URL launcher
  url_launcher:

# Image carousel
  carousel_pro :

# Font awesome
  font_awesome_flutter:

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/
